name: flutex
description: Flutter and Dart extensions
version: 0.0.1
author: Vladislav Zhukov
homepage: https://github.com/mrxten/flutex

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"